### ISSUE TITLE
Missing dependencies to pda/pheanstalk in composer.json

### ISSUE THREAD

**Issue by dfeyer** [etg24/EventSourcing#7]
With this dependency Flow throw an Exception: 

> Tried to configure unknown object "Pheanstalk\Pheanstalk" in package "Etg24.EventSourcing".
> Please check your Objects.yaml

"pda/pheanstalk": "3.0.*"

**Comment by Akii** [comment]
Fixed with 4d1bb94465dd6bd1206c04f5a696b3195d30ed5a.
